# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6281ed2242160bc82455b33ebcca4a9920a07973f2351ee4192212cff45b52e566d600a161feede55c7daef9da58b0ecd181aa8270cf9d7e3ab6abc6daf50642

test:
  secret_key_base: eba9f379c16d81324ceac9f59ae72172b5b0d530c4f7f0a82005cc7d293213f3e01e086e4a26ee090e7e90eacd99e69c0557aa4e51de4926cc9444982e7a0c8f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
